const taskCounts = {
  LTAA: {
    "Induction Preparation": 3,
    Induction: 6,
    "Incoming Inspection": 1,
    Disassembly: 4,
    Provisioning: 3,
    "Work Planning": 0,
    "Work Execution / Repair": 5,
    Assembly: 1,
    "Monitoring / Event Monitoring": 2,
    "Outgoing / Outgoing Documentation": 1,
    "Finish MRO Event": 2,
    Total: 28,
  },
  HPUS: {
    "Induction Preparation": 3,
    Induction: 8,
    "Incoming Inspection": 1,
    Disassembly: 3,
    Provisioning: 3,
    "Work Planning": 2,
    "Work Execution / Repair": 8,
    Assembly: 1,
    "Monitoring / Event Monitoring": 3,
    "Outgoing / Outgoing Documentation": 4,
    "Finish MRO Event": 3,
    Total: 39,
  },
  LTLGS: {
    "Induction Preparation": 3,
    Induction: 8,
    "Incoming Inspection": 1,
    Disassembly: 3,
    Provisioning: 3,
    "Work Planning": 2,
    "Work Execution / Repair": 7,
    Assembly: 1,
    "Monitoring / Event Monitoring": 3,
    "Outgoing / Outgoing Documentation": 3,
    "Finish MRO Event": 3,
    Total: 37,
  },
};
